services:
  postgres:
    container_name: postgres
    image: postgres:15 # Or a later version
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432' # Map container port 5432 to host port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres-data: # Define the named volume for database persistence

